[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
ticket_fields = { path = "../../../helpers/ticket_fields" }
axum = { version = "0.8.4", features = ["macros"] }
axum-macros = "0.5.0"
serde = {version = "1.0.226", features = ["derive"] }
tracing-subscriber = "0.3.20"
